nombre = input("Introduce tu nombre, por favor : ")
print(f"Hola, {nombre}")
edad = int(input(" Ingresa tu edad, por favor : "))
print(f"Has vivido {edad * 12} meses")
print(f"Has vivido {((edad * 365)*24)* 3600} segundos")